language: objective-c
os: osx
install:
  - brew install npm
  - brew install imagemagick
  - sudo npm install cordova -g
  - sudo npm install cordova-splash -g
  - sudo npm install cordova-icon -g
script:
  - cordova platform add ios
  - cordova build
